version: "3.8"
services:
  ollama-service:
    build:
      context: ./Ollama
      dockerfile: Dockerfile
    ports: 
      - "11434:11434"
  
  fastapi-service:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    depends_on:
      - ollama-service
    ports:
      - "8000:8000"
    
  streamlit-service:
    build:
      context: ./StreamlitUI
      dockerfile: Dockerfile
    depends_on:
      - fastapi-service
    ports:
      - "8501:8501"

