version: "3.8"
services:
  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
  
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    
  streamlit:
    build:
      context: ./StreamlitUI
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    ports:
      - "8501:8501"

